### ISSUE TITLE
[Bug] Cancle button don't show

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/translation-manager#13]
# Bug report

### What I did

Revert 1 record
![image](https://github.com/Laravel-Backpack/translation-manager/assets/101564593/5bfc21bd-b27e-4028-b4b7-df41ce007af7)

### What I expected to happen

The **Cancle button** displays under all supported Backpack interfaces

#### Light theme
![image](https://github.com/Laravel-Backpack/translation-manager/assets/101564593/755c9265-4ad0-495f-a8f2-06bc39a6c44f)
#### Dark theme
![image](https://github.com/Laravel-Backpack/translation-manager/assets/101564593/783e737e-1183-4c46-8d78-c244fe987822)

### What I've already tried to fix it

Old issue in new package. Good luck!!!
https://github.com/Laravel-Backpack/theme-tabler/issues/160

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.3.4

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, swoole, Zend OPcache, xdebug

### LARAVEL VERSION:
11.3.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.3
backpack/backupmanager: v5.0.2
backpack/basset: 1.3.0
backpack/crud: 6.7.5
backpack/filemanager: 3.0.7
backpack/generators: v4.0.5
backpack/language-switcher: 2.0.0
backpack/logmanager: v5.0.1
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.0
backpack/pro: 2.1.12
backpack/revise-operation: 2.0.0
backpack/theme-tabler: 1.2.8
backpack/translation-manager: 1.0.1
```

**Comment by pxpm** [comment]
Thanks for the heads up @tringuyenduc2903 🙏 

Fixed in #15 

Will merge and tag a new release in a short time. 

Cheers
