### ISSUE TITLE
Issue with Badge Styling in Key Column Using backpack/theme-coreuiv4 with Laravel-Backpack/Translation-Manager

### ISSUE THREAD

**Issue by adrinro** [Laravel-Backpack/translation-manager#23]
Hello,

I am using the `backpack/theme-coreuiv4` theme in the `Laravel-Backpack/translation-manager` package and have noticed an issue with the styles in the "key" column.

The `badge` class does not have a defined background color and the text is in white, making the text illegible. I believe this is a styling error that should be corrected.

![image](https://github.com/user-attachments/assets/d29483b0-692f-4baa-81b9-5f316a470cb9)

As a temporary solution, I have added the `bg-info` class to the `badge` class  in the `TranslationManagerCrudController` and this has resolved the issue.

![image](https://github.com/user-attachments/assets/b00430f2-711f-4769-86a3-8f5daff3f778)

Thank you for your attention to this matter.

Best regards,

**Comment by jcastroa87** [comment]
Hello @adrinro 

Thanks for this information, i confirm this as a bug, i checked in our demo.

<img width="1395" alt="Screenshot 2024-07-16 at 8 01 04 AM" src="https://github.com/user-attachments/assets/46cd12a2-9307-4567-912e-2810fd91e4f5">

I will assign to @pxpm.

Thanks again.

Cheers.

**Comment by pxpm** [comment]
Thanks for the report @adrinro 

I've just pushed a change in the badge styling that should work by default in all themes. 

Let us know if you experience other issues 👍 

Cheers
