### ISSUE TITLE
New Addon: Edit Laravel Translations from Your Admin Panel.

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/translation-manager#9]
Add-on Launch checklist:
- [x] finish all v1 features;
- [x] tag 1.0.0;
- [x] make sure README.md is has clear description, screenshot, instructions;
- [x] make sure LICENSE.md is correct (MIT for open-source, EULA for closed-source);
- [x] give Write access to the entire team on Github;
- [x] add to [Packagist](https://packagist.org/packages/backpack/) (if open-source) or our [private Satis](https://repo.backpackforlaravel.com/) (if closed-source);
- [ ] ~~if closed-source, add to Backpack website as paid product (so people can buy it); consider having a launch discount (50%);~~
- [ ] ~~if closed-source, add to [Backpack pricing page](https://backpackforlaravel.com/pricing);~~
- [x] include in [our add-ons page](https://backpackforlaravel.com/addons); 
- [x] mention it [in our docs](https://backpackforlaravel.com/docs/6.x/add-ons-official);
- [x] write a [blog](https://backpackforlaravel.com/articles/tutorials/new-addon-edit-laravel-translations-from-your-admin-panel) post about it;
- [ ] tweet about it (schedule 3 tweets - launch tweet, reminder tweet after a few weeks, reminder tweet after a few months);
- [x] submit the add-on to directories like [madewithlaravel.com](http://madewithlaravel.com/)
- [ ] submit to Laravel News
- [ ] Promote

**Comment by tabacitu** [comment]
@karandatwani92 I think I'm done here for the time being. We need 
- [ ] tweets 
- [ ] article

Then you can assign it back to me, to submit the link to Laravel News (waiting for one to be approved first).

**Comment by karandatwani92** [comment]
Hey @tabacitu 

Yes, They are ready.

Please review:
https://hackmd.io/cplcMWUpRLi6jx1fT00Z2A

**Comment by pxpm** [comment]
This is done right ? If not please reopen and finish it @karandatwani92 🙏
